# Site settings
name: DAI Lab Open Source
title: DAI Lab Open Source Libraries
email: info@email.com
description: > # this means to ignore newlines until "baseurl:"
  DAI Lab Open Source Libraries
baseurl: "opensource" # the subpath of your site, e.g. /blog/
url: "https://dai-lab.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

# Build settings
markdown: kramdown

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - README.md
  - .jekyll-cache
  - bootstrap-vars.scss

keep_files:
  - _site/css
  - _site/js

include: ['_pages']